USE [StgArea]
GO

/****** Object:  Table [dbo].[Tb_Stg_Claro_25a44]    Script Date: 07/05/2019 13:26:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tb_Stg_Claro_25a44](
	[CAMPAIGN_CD] [varchar](50) NULL,
	[RESPTRACKING_CD] [varchar](50) NULL,
	[ID_DOMICILIO] [varchar](50) NULL,
	[CD_OPERADORA] [varchar](50) NULL,
	[CD_NET] [varchar](50) NULL,
	[NUM_DBM] [varchar](50) NULL,
	[NUM_DBM_HH] [varchar](50) NULL,
	[TELEFONE_VOIP] [varchar](50) NULL,
	[TELEFONE_RESIDENCIAL] [varchar](50) NULL,
	[TELEFONE_CELULAR] [varchar](50) NULL,
	[TELEFONE_COMERCIAL] [varchar](50) NULL,
	[TELEFONE_CLARO_1] [varchar](50) NULL,
	[TELEFONE_CLARO_2] [varchar](50) NULL,
	[TELEFONE_CLARO_3] [varchar](50) NULL,
	[TELEFONE_1] [varchar](50) NULL,
	[TELEFONE_2] [varchar](50) NULL,
	[TELEFONE_3] [varchar](50) NULL,
	[NOME] [varchar](100) NULL,
	[TP_LOGR] [varchar](50) NULL,
	[LOGR] [varchar](50) NULL,
	[NUM] [varchar](50) NULL,
	[COMPL] [varchar](50) NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADE] [varchar](50) NULL,
	[UF] [varchar](50) NULL,
	[CEP] [varchar](50) NULL,
	[SEL_PTV] [varchar](50) NULL,
	[PCT_VIRTUA] [varchar](50) NULL,
	[VEL] [varchar](50) NULL,
	[POSSUI_PPV_FUTEBOL] [varchar](50) NULL,
	[POSSUI_PPV_FILME] [varchar](50) NULL,
	[POSSUI_PPV_OUTRO] [varchar](50) NULL,
	[POSSUI_DEB_CONTA] [varchar](50) NULL,
	[POSSUI_A_LA_CARTE] [varchar](50) NULL,
	[CLASSE_SOCIAL] [varchar](50) NULL,
	[SEGMENTO] [varchar](100) NULL,
	[OFERTA_PRODUTO_1] [varchar](50) NULL,
	[OFERTA_PRODUTO_2] [varchar](50) NULL,
	[OPORTUNIDADE_NBO_1] [varchar](50) NULL,
	[OPORTUNIDADE_NBO_2] [varchar](50) NULL,
	[OPORTUNIDADE_NBO_3] [varchar](50) NULL,
	[NODE_BID_UNI] [varchar](50) NULL,
	[AREA_TEC_NODE] [varchar](50) NULL,
	[NM_NODE] [varchar](50) NULL,
	[VL_PTV_3] [varchar](50) NULL,
	[VL_VTA_3] [varchar](50) NULL,
	[VL_PONTO_ADICIONAL_2] [varchar](50) NULL,
	[VL_MENSALIDADE_2] [varchar](50) NULL,
	[STATUS_EBT] [varchar](50) NULL,
	[MIX_PRODUTOS] [varchar](50) NULL,
	[DT_INSTALACAO_EXPORT] [varchar](50) NULL,
	[DT_AQ_PRD_TV_ATUAL] [varchar](50) NULL,
	[DT_VENC_FAT] [varchar](50) NULL,
	[TIPO_PESSOA] [varchar](50) NULL,
	[CPF_CNPJ] [varchar](50) NULL,
	[TIPO_CONTRATO] [varchar](50) NULL,
	[PROPENSAO] [varchar](50) NULL,
	[CORINGA_1] [varchar](100) NULL,
	[CORINGA_2] [varchar](100) NULL,
	[CORINGA_3] [varchar](100) NULL,
	[CORINGA_4] [varchar](50) NULL,
	[CORINGA_5] [varchar](50) NULL,
	[CORINGA_6] [varchar](50) NULL,
	[CORINGA_7] [varchar](50) NULL,
	[CORINGA_8] [varchar](50) NULL,
	[CORINGA_9] [varchar](50) NULL,
	[CORINGA_10] [varchar](50) NULL,
	[CORINGA_11] [varchar](50) NULL,
	[CORINGA_12] [varchar](50) NULL,
	[CORINGA_13] [varchar](50) NULL,
	[CORINGA_14] [varchar](50) NULL,
	[CORINGA_15] [varchar](50) NULL,
	[CORINGA_16] [varchar](50) NULL,
	[CORINGA_17] [varchar](50) NULL,
	[DT_INICIO_VIGENCIA] [varchar](50) NULL,
	[DT_FIM_VIGENCIA] [varchar](50) NULL
) ON [PRIMARY]
GO


