USE [StgArea]
GO

/****** Object:  Table [dbo].[Tb_Stg_Crefisa]    Script Date: 07/05/2019 13:26:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tb_Stg_Crefisa](
	[CARTEIRA] [varchar](100) NULL,
	[SCOREESCRITORIO] [varchar](100) NULL,
	[NUMEROCONTRATO] [varchar](100) NULL,
	[FXVALOR] [varchar](100) NULL,
	[FXAVISTA] [varchar](100) NULL,
	[VENCIMENTO DE DEBITO] [varchar](100) NULL,
	[ATRASO] [varchar](100) NULL,
	[DATA_ENTRADA] [varchar](100) NULL,
	[DATA_DEVOLUCAO] [varchar](100) NULL,
	[ACIONADO] [varchar](100) NULL,
	[DATA_ULT_ACIONAMENTO] [varchar](100) NULL,
	[LIGACAO] [varchar](100) NULL,
	[DATA_ULT_LIGACAO] [varchar](100) NULL,
	[BOLETADO] [varchar](100) NULL,
	[DATA_ULT_BOLETAGEM] [varchar](100) NULL,
	[A_SMS] [varchar](100) NULL,
	[SMS_ENVIADO] [varchar](100) NULL,
	[DATA_ULT_SMS] [varchar](100) NULL,
	[A_URA] [varchar](100) NULL,
	[URA_ENVIADA] [varchar](100) NULL,
	[DATA_ULT_URA] [varchar](100) NULL,
	[COMBO_RSU] [varchar](100) NULL,
	[STATUS_CONTRATO] [varchar](100) NULL,
	[STATUS_ACIONAMENTO] [varchar](100) NULL,
	[TENTATIVAS] [varchar](100) NULL,
	[LIGACOES] [varchar](100) NULL,
	[CONTATOS] [varchar](100) NULL,
	[PROMESSAS] [varchar](100) NULL,
	[SCORE _Contratante] [varchar](100) NULL,
	[UF] [varchar](100) NULL,
	[DATA_AGENDAMENTO] [varchar](100) NULL,
	[EMAIL] [varchar](100) NULL,
	[Retorno_Agendamento] [varchar](100) NULL,
	[COD_CAMPANHA] [varchar](100) NULL,
	[CLUSTER] [varchar](100) NULL,
	[TALK_LIGACOES_HOJE] [varchar](100) NULL,
	[TELEFONE_CELULAR_EFETIVO1] [varchar](100) NULL,
	[TELEFONE_CELULAR_EFETIVO2] [varchar](100) NULL,
	[TELEFONE_CELULAR_EFETIVO3] [varchar](100) NULL,
	[TELEFONE_FIXO_EFETIVO1] [varchar](100) NULL,
	[TELEFONE_FIXO_EFETIVO2] [varchar](100) NULL,
	[TELEFONE_FIXO_EFETIVO3] [varchar](100) NULL,
	[TELEFONE_CELULAR_1] [varchar](100) NULL,
	[TELEFONE_CELULAR_2] [varchar](100) NULL,
	[TELEFONE_CELULAR_3] [varchar](100) NULL,
	[TELEFONE_RESIDENCIAL1] [varchar](100) NULL,
	[TELEFONE_RESIDENCIAL2] [varchar](100) NULL,
	[TELEFONE_RESIDENCIAL3] [varchar](100) NULL,
	[TELEFONE_COMERCIAL1] [varchar](100) NULL,
	[TELEFONE_COMERCIAL2] [varchar](100) NULL,
	[TELEFONE_COMERCIAL3] [varchar](100) NULL,
	[TELEFONE_OUTROS1] [varchar](100) NULL,
	[TELEFONE_OUTROS2] [varchar](100) NULL,
	[TELEFONE_OUTROS3] [varchar](100) NULL,
	[Estratégia] [varchar](100) NULL,
	[NOME] [varchar](100) NULL,
	[FILLER] [varchar](100) NULL,
	[OPERADOR] [varchar](100) NULL,
	[TEL_AGENDA] [varchar](100) NULL,
	[DATA_AGENDAMENTO_1] [varchar](100) NULL,
	[CPF] [varchar](100) NULL,
	[ID_CONTRATO] [varchar](100) NULL,
	[REGIAO] [varchar](100) NULL,
	[PRODUTO] [varchar](100) NULL,
	[CONTRATANTE] [varchar](100) NULL,
	[RECUP_FICTICIO] [varchar](100) NULL,
	[ATRASO_CONGELADO] [varchar](100) NULL,
	[TELEFONE_COMERCIAL_EFETIVO1] [varchar](100) NULL,
	[TELEFONE_COMERCIAL_EFETIVO2] [varchar](100) NULL,
	[TELEFONE_COMERCIAL_EFETIVO3] [varchar](100) NULL,
	[TELEFONE_PESQUISADO1] [varchar](100) NULL,
	[TELEFONE_PESQUISADO2] [varchar](100) NULL,
	[TELEFONE_PESQUISADO3] [varchar](100) NULL,
	[TELEFONE_PESQUISADO4] [varchar](100) NULL,
	[TELEFONE_PESQUISADO5] [varchar](100) NULL,
	[TELEFONE_PESQUISADO6] [varchar](100) NULL,
	[TELEFONE_PESQUISADO7] [varchar](100) NULL,
	[TELEFONE_PESQUISADO8] [varchar](100) NULL,
	[TELEFONE_PESQUISADO9] [varchar](100) NULL,
	[TELEFONE_PESQUISADO10] [varchar](100) NULL,
	[FILA_DE_COBRANCA] [varchar](100) NULL,
	[DATA_VENCIMENTO] [varchar](100) NULL,
	[VALOR_PARCELA_VENCIDA] [varchar](100) NULL,
	[VALOR_PARCELA_A_VENCER] [varchar](100) NULL
) ON [PRIMARY]
GO


